"""add progress_baseline to savings_goal

Revision ID: 0d63fbcf288e
Revises: 4faa6deddcc2
Create Date: 2026-02-23 15:30:31.673905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d63fbcf288e'
down_revision = '4faa6deddcc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_baseline', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_goal', schema=None) as batch_op:
        batch_op.drop_column('progress_baseline')

    # ### end Alembic commands ###
