"""add base_user_id and grocery_item

Revision ID: 14a4d39f7b23
Revises: e4906456ef59
Create Date: 2026-02-07 14:43:48.571416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a4d39f7b23'
down_revision = 'e4906456ef59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chore_base_user_id', 'user', ['base_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chore_base_user_id', type_='foreignkey')
        batch_op.drop_column('base_user_id')

    op.drop_table('grocery_item')
    # ### end Alembic commands ###
