"""add_mission_reward_and_gem_columns

Revision ID: e2ab84ba35bf
Revises: 596dafc9831b
Create Date: 2026-02-23 11:44:06.478944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ab84ba35bf'
down_revision = '596dafc9831b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_xp', sa.Integer(), nullable=False, server_default='500'))
        batch_op.add_column(sa.Column('reward_description', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('gem_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gem_size', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('gem_size')
        batch_op.drop_column('gem_type')
        batch_op.drop_column('reward_description')
        batch_op.drop_column('reward_xp')

    # ### end Alembic commands ###
